on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_ppc:
    runs-on: ubuntu-latest
    container:
      image: walkero/docker4amigavbcc:latest-ppc
    name: build_os4
    steps:
      - uses: actions/checkout@v2
      - name: build_os4
        id: build_os4
        run: |
          vc +newlib -o envClock_OS4 envclock.c -lauto
      - uses: actions/upload-artifact@v2
        with:
          name: envClock_OS4
          path: ./envClock_OS4
  build_68k:
    runs-on: ubuntu-latest
    container:
      image: walkero/docker4amigavbcc:latest-m68k
    name: build_os3
    steps:
      - uses: actions/checkout@v2
      - name: build_os3
        id: build_os3
        run: |
          vc +aos68k -o envClock_OS3 envclock.c
      - uses: actions/upload-artifact@v2
        with:
          name: envClock_OS3
          path: ./envClock_OS3
